adding pushall option, to push all the repos in the cwd

diff --git a/bin/freshen_repos b/bin/freshen_repos
--- a/bin/freshen_repos
+++ b/bin/freshen_repos
@@ -14,7 +14,6 @@ gpa() {
 	git checkout $GIT_CURRENT
 	cd $GIT_CURRENTDIR
 	}
-
 freshen_repos() {
 	AMIGITREPO=`git status 2>&1 > /dev/null`
 	RC=$?
@@ -39,6 +38,31 @@ freshen_repos() {
 		fi
 		done
 	}
+push_repos() {
+	AMIGITREPO=`git status 2>&1 > /dev/null`
+	RC=$?
+	if [ $RC = 0 ]
+	then
+		echo "In a git repo already"
+		git push
+		exit
+	fi
+	for repo in *
+		do
+		echo " ======== ${repo} ========= "
+		echo " "
+		if [ -d $repo ]
+		then
+		cd $repo
+			git push
+			cd ../
+		else
+			echo " ${repo} Not a dir, so can't be a repo"
+		echo " "
+		fi
+		done
+	}
+
 
 base="$(basename "$0")"
 case $base in
@@ -47,6 +71,9 @@ case $base in
 	;;
 	gpa)
 		gpa
+	;;
+	pushall)
+		push_repos
 	;;
 	*)
 		echo "Catchall, try again"
